# 主分支构建发布
name: build-app
on:
    push:
        tags:
            - 'v*'

jobs:
    # ========================= 准备项目 =========================
    init:
        name: 初始化构建
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.step_init.outputs.VERSION }}
            git_hash: ${{ steps.step_hash.outputs.HASH }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Init Env
              id: step_init
              run: |
                TAG=${{ github.ref_name }}
                VERSION=${TAG#v}
                echo VERSION=$VERSION >> $GITHUB_OUTPUT
            - name: Get Git Hash
              id: step_hash
              run: |
                TAG=${{ github.ref_name }}
                if [[ $TAG == *"-dev-"* ]]; then
                  HASH=${TAG#*-dev-}
                else
                  HASH=$(git rev-parse --short HEAD)
                fi
                echo HASH=$HASH >> $GITHUB_OUTPUT

    # ========================= 构建 Web 版本 =========================
    build-root-web:
        needs: init
        uses: ./.github/workflows/build-web.yml
        with:
            version: ${{ needs.init.outputs.version }}
            git_hash: ${{ needs.init.outputs.git_hash }}

    # ========================= 构建 Tauri 版本 =========================
    build-tauri:
        needs: init
        uses: ./.github/workflows/build-tauri.yml
        with:
            version: ${{ needs.init.outputs.version }}
            git_hash: ${{ needs.init.outputs.git_hash }}
        secrets: inherit

    # ========================= 构建 Android 版本 =========================
    build-android:
        needs: init
        uses: ./.github/workflows/build-android.yml
        with:
            version: ${{ needs.init.outputs.version }}
            git_hash: ${{ needs.init.outputs.git_hash }}
        secrets: inherit

    # ========================= 构建 iOS 版本 =========================
    build-ios:
        needs: init
        uses: ./.github/workflows/build-ios.yml
        with:
            version: ${{ needs.init.outputs.version }}
            git_hash: ${{ needs.init.outputs.git_hash }}
        secrets: inherit

    # ========================= 发布构建结果 =========================
    release:
        name: 发布构建结果
        runs-on: ubuntu-latest
        needs:
            - init
            - build-root-web
            - build-tauri
            - build-android
            - build-ios
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  path: artifacts
                  pattern: Stapxs-QQ-Lite-v${{ needs.init.outputs.version }}-*
                  merge-multiple: false
            - name: Publish Release
              env:
                GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              run: |
                gh release view v${{ needs.init.outputs.version }} || gh release create v${{ needs.init.outputs.version }} --title "Release v${{ needs.init.outputs.version }}" --generate-notes
                gh release upload v${{ needs.init.outputs.version }} artifacts/**/* --clobber
